# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:  # permite execução manual
  # release:
  #   types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install and Build package
        run: |
          npm ci --ignore-scripts
          npm run build

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Show successfull publish
        if: success()
        run: echo "📦 Published to NPM -> ${{ github.event.release.tag_name }}"
        
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=20.x'
          registry-url: https://npm.pkg.github.com/
          cope: ${{ github.repository_owner }}
          cache: 'npm'
          
      - name: Install and Build package
        run: |
          npm ci --ignore-scripts
          npm run build

      - name: Verify Package
        run: npm pack --dry-run

      - name: Publish to GitHub Packages
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show successfull publish
        if: success()
        run: echo "📦 Published to GHP -> ${{ github.event.release.tag_name }}"
